# env:
 # TERM: xterm-256color
 # TERM: alacritty

font:
  normal:
    family: JetBrainsMono Nerd Font
    style: Regular

  bold:
    family: JetBrainsMono Nerd Font 
    style: Bold

  italic:
    family: JetBrainsMono Nerd Font
    style: Italic

  bold_italic:
    family: JetBrainsMono Nerd Font
    style: Bold Italic

  size: 13
  offset:
    x: 1
    y: 6
  glyph_offset:
    x: 0
    y: 3

custom_cursor_colors: true

window:
  dynamic_padding: false
  option_as_alt: OnlyLeft
  padding:
    x: 0
    y: 0

cursor:
  unfocused_hollow: true
  # thickness: 0.2

colors:
  cursor:
    cursor: '0xbdad93'
  primary:
    background: '0x282828'
    foreground: '0xebdbb2'

  # Normal colors
  normal:
    black:   '0x282828'
    red:     '0xcc241d'
    green:   '0x98971a'
    yellow:  '0xd79921'
    blue:    '0x458588'
    magenta: '0xb16286'
    cyan:    '0x689d6a'
    white:   '0xa89984'

  # Bright colors
  bright:
    black:   '0x928374'
    red:     '0xfb4934'
    green:   '0xb8bb26'
    yellow:  '0xfabd2f'
    blue:    '0x83a598'
    magenta: '0xd3869b'
    cyan:    '0x8ec07c'
    white:   '0xebdbb2'

key_bindings:
  - { key: 'PageUp', mods: Shift|Control, mode: ~Search, action: ToggleViMode }
  - { key: F, mods: Command|Control, action: ToggleFullscreen }
  - { key: Key6, mods: Control, chars: "\x1e" }
